spring:
  application:
    name: LeanTechKafka
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/leantechkafka
    username: leantechkafka_admin
    password: 12345
  flyway:
    url: jdbc:postgresql://localhost:5432/leantechkafka
    user: leantechkafka_admin
    password: 12345
    schemas: notifications
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: ru.fendel.leantechkafka.web.dto.NotificationRequestDto

app:
  kafka:
    topic:
      name: notifications-topic